name:                Quail
version:             0.1.0.0
github:              "wvogel00/Quail"
license:             BSD3
author:              "wataru torii"
maintainer:          "wtorii@hey.com"
copyright:           "2020 W.TORII"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            application for music composition
# category:            App

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wvogel00/Quail#readme>

dependencies:
- base >= 4.7 && < 5
- sdl2 >= 2.5.0.0
- sdl2-ttf
- sdl2-image
- extra
- linear >= 1.21
- process
- text
- vector
- lens
- directory
- filepath

library:
  source-dirs: src

executables:
  Quail-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Quail

tests:
  Quail-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Quail
